version: '3.8'
services:
    arches:
      container_name: dev_arches
      image: 741f71bf1dcf
      build:
        context: .
        dockerfile: ./Dockerfile
      command: init_arches
      env_file:
        - ./docker/env_file.env
      ports:
      #change this to avoid conflicts with other projects
        - 8000:8000
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches_dev

volumes:
    arches-log:
    arches-static:
